# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'race.ui'
#
# Created: Sun Jul 15 04:24:19 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(640, 480)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.listView = QtGui.QListView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setFrameShadow(QtGui.QFrame.Sunken)
        self.listView.setResizeMode(QtGui.QListView.Fixed)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.horizontalLayout_2.addWidget(self.listView)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.toolMenu = QtGui.QMenu(self.menubar)
        self.toolMenu.setObjectName(_fromUtf8("toolMenu"))
        self.helpMenu = QtGui.QMenu(self.menubar)
        self.helpMenu.setObjectName(_fromUtf8("helpMenu"))
        self.fileMenu = QtGui.QMenu(self.menubar)
        self.fileMenu.setObjectName(_fromUtf8("fileMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionRace_Configuration = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/clear/128x128/actions/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRace_Configuration.setIcon(icon)
        self.actionRace_Configuration.setObjectName(_fromUtf8("actionRace_Configuration"))
        self.actionOpen_Race = QtGui.QAction(MainWindow)
        self.actionOpen_Race.setCheckable(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/clear/128x128/actions/stock_paste.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Race.setIcon(icon1)
        self.actionOpen_Race.setObjectName(_fromUtf8("actionOpen_Race"))
        self.actionSave_Race = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/clear/128x128/actions/stock_save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Race.setIcon(icon2)
        self.actionSave_Race.setObjectName(_fromUtf8("actionSave_Race"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/clear/128x128/actions/stock_save-as.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon3)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionClose = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("exit"))
        self.actionClose.setIcon(icon)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("gtk-find"))
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionNew_Race = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/clear/128x128/actions/stock_new-text.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_Race.setIcon(icon4)
        self.actionNew_Race.setObjectName(_fromUtf8("actionNew_Race"))
        self.actionVentana_Cronometro = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/clear/128x128/actions/window-new.png")), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.actionVentana_Cronometro.setIcon(icon5)
        self.actionVentana_Cronometro.setObjectName(_fromUtf8("actionVentana_Cronometro"))
        self.actionCronometro_Fullscreen = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/clear/128x128/actions/stock_fullscreen.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCronometro_Fullscreen.setIcon(icon6)
        self.actionCronometro_Fullscreen.setObjectName(_fromUtf8("actionCronometro_Fullscreen"))
        self.toolMenu.addAction(self.actionRace_Configuration)
        self.helpMenu.addAction(self.actionAbout)
        self.fileMenu.addAction(self.actionNew_Race)
        self.fileMenu.addAction(self.actionOpen_Race)
        self.fileMenu.addAction(self.actionSave_Race)
        self.fileMenu.addAction(self.actionSave_As)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.actionClose)
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.toolMenu.menuAction())
        self.menubar.addAction(self.helpMenu.menuAction())
        self.toolBar.addAction(self.actionNew_Race)
        self.toolBar.addAction(self.actionOpen_Race)
        self.toolBar.addAction(self.actionSave_Race)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRace_Configuration)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionVentana_Cronometro)
        self.toolBar.addAction(self.actionCronometro_Fullscreen)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Cronometro", None, QtGui.QApplication.UnicodeUTF8))
        self.toolMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Herramientas", None, QtGui.QApplication.UnicodeUTF8))
        self.helpMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.fileMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRace_Configuration.setText(QtGui.QApplication.translate("MainWindow", "Configurar Carrera", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Race.setText(QtGui.QApplication.translate("MainWindow", "Abrir Carrera", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Race.setText(QtGui.QApplication.translate("MainWindow", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Guardar Como...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Cerrar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "Sobre", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Race.setText(QtGui.QApplication.translate("MainWindow", "Nueva Carrera", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVentana_Cronometro.setText(QtGui.QApplication.translate("MainWindow", "Ventana Cronometro", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCronometro_Fullscreen.setText(QtGui.QApplication.translate("MainWindow", "Cronometro Fullscreen", None, QtGui.QApplication.UnicodeUTF8))

import toolbar_rc
